<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks Condition="'$(OS)' == 'Windows_NT'">net472;$(TargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <Import Project="..\..\src\Xunit.DependencyInjection\Xunit.DependencyInjection.targets" />
  <Import Project="..\TestPackages.targets" />

  <ItemGroup>
    <Using Include="Xunit.Sdk" />

    <Compile Include="../Xunit.DependencyInjection.Test/RunMonitorCollectionLastOrderer.cs" />
    <Compile Include="../Xunit.DependencyInjection.Test.DisableTestParallelization/*.cs" />

    <PackageReference Include="Shouldly" />

    <ProjectReference Include="..\..\src\Xunit.DependencyInjection\Xunit.DependencyInjection.csproj" />
  </ItemGroup>

</Project>
