//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xunit.DependencyInjection.Analyzer {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xunit.DependencyInjection.Analyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Startup must not more than one public constructor. 的本地化字符串。
        /// </summary>
        internal static string MultipleConstructorDescription {
            get {
                return ResourceManager.GetString("MultipleConstructorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Startup &apos;{0}&apos; must has public multiple constructors. 的本地化字符串。
        /// </summary>
        internal static string MultipleConstructorMessageFormat {
            get {
                return ResourceManager.GetString("MultipleConstructorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Startup must has public multiple constructors. 的本地化字符串。
        /// </summary>
        internal static string MultipleConstructorTitle {
            get {
                return ResourceManager.GetString("MultipleConstructorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Having multiple overloads is not supported. 的本地化字符串。
        /// </summary>
        internal static string MultipleOverloadsDescription {
            get {
                return ResourceManager.GetString("MultipleOverloadsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Having multiple overloads of method &apos;{methodName}&apos; is not supported. 的本地化字符串。
        /// </summary>
        internal static string MultipleOverloadsMessageFormat {
            get {
                return ResourceManager.GetString("MultipleOverloadsMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method not supported multiple overloads. 的本地化字符串。
        /// </summary>
        internal static string MultipleOverloadsTitle {
            get {
                return ResourceManager.GetString("MultipleOverloadsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method must have no return type. 的本地化字符串。
        /// </summary>
        internal static string NoReturnTypeDescription {
            get {
                return ResourceManager.GetString("NoReturnTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The &apos;{0}&apos; method must have no return type. 的本地化字符串。
        /// </summary>
        internal static string NoReturnTypeMessageFormat {
            get {
                return ResourceManager.GetString("NoReturnTypeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method must return type is not void. 的本地化字符串。
        /// </summary>
        internal static string NoReturnTypeTitle {
            get {
                return ResourceManager.GetString("NoReturnTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method should not be static. 的本地化字符串。
        /// </summary>
        internal static string NotStaticMethodDescription {
            get {
                return ResourceManager.GetString("NotStaticMethodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method &apos;{0}&apos; should not be static. 的本地化字符串。
        /// </summary>
        internal static string NotStaticMethodMessageFormat {
            get {
                return ResourceManager.GetString("NotStaticMethodMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method is static. 的本地化字符串。
        /// </summary>
        internal static string NotStaticMethodTitle {
            get {
                return ResourceManager.GetString("NotStaticMethodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Startup must have a single parameterless public constructor. 的本地化字符串。
        /// </summary>
        internal static string ParameterlessConstructorDescription {
            get {
                return ResourceManager.GetString("ParameterlessConstructorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constructor has parameter(s). 的本地化字符串。
        /// </summary>
        internal static string ParameterlessConstructorMessageFormat {
            get {
                return ResourceManager.GetString("ParameterlessConstructorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constructor has parameter(s). 的本地化字符串。
        /// </summary>
        internal static string ParameterlessConstructorTitle {
            get {
                return ResourceManager.GetString("ParameterlessConstructorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method must parameterless or have the single parameter. 的本地化字符串。
        /// </summary>
        internal static string ParameterlessOrSingleParameterDescription {
            get {
                return ResourceManager.GetString("ParameterlessOrSingleParameterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The &apos;{0}&apos; method must parameterless or have the single &apos;{1}&apos; parameter. 的本地化字符串。
        /// </summary>
        internal static string ParameterlessOrSingleParameterMessageFormat {
            get {
                return ResourceManager.GetString("ParameterlessOrSingleParameterMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method parameters is to much. 的本地化字符串。
        /// </summary>
        internal static string ParameterlessOrSingleParameterTitle {
            get {
                return ResourceManager.GetString("ParameterlessOrSingleParameterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method must return type must be a sub type of a specific type. 的本地化字符串。
        /// </summary>
        internal static string ReturnTypeAssignableToDescription {
            get {
                return ResourceManager.GetString("ReturnTypeAssignableToDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The &apos;{0}&apos; method return type must assignable to &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ReturnTypeAssignableToMessageFormat {
            get {
                return ResourceManager.GetString("ReturnTypeAssignableToMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method must return type is invalid. 的本地化字符串。
        /// </summary>
        internal static string ReturnTypeAssignableToTitle {
            get {
                return ResourceManager.GetString("ReturnTypeAssignableToTitle", resourceCulture);
            }
        }
    }
}
